version: "3"
services: 
  factorio:
    build: . 
    image: jugganourt/factorio:1.0.0
    container_name: "factorio"
    volumes: 
      - "/docker/factorio/saves:/home/factorio/saves"
      - "/docker/factorio/mods:/home/factorio/mods "
      - "/docker/factorio/settings:/home/factorio/settings"
    ports: 
      - "34197:34197/udp"
      - "27015:27015/tcp"
    restart: alwasys